version: '3.8'

services:
  cache:
    container_name: hits-redis
    image: redis:latest 
    environment:
      - "REDIS_ARGS=--appendonly yes"
    ports:
      - "8786:6379"
    volumes:
      - hits_redis_data:/data
    restart: always

volumes:
  hits_redis_data:
