version: '3.8'

services:
  app:
    build: .
    ports:
      - "8787:8787"
    environment:
      - REDIS_URL=redis://cache:6379
    restart: always

  cache:
    image: redis:latest 
    environment:
      - "REDIS_ARGS=--appendonly yes"
    # ports:
    #   - "8786:6379"
    volumes:
      - hits_redis_data:/data
    restart: always

volumes:
  hits_redis_data:
