version: '3.8'

services:
  app:
    build: .
    expose:
      - "8787"
    # ports:
    #   - "8787:8787"
    environment:
      - REDIS_URL=redis://cache:6379
    restart: always
    networks:
      - hits_network

  cache:
    image: redis:latest 
    environment:
      - "REDIS_ARGS=--appendonly yes"
    # ports:
    #   - "8786:6379"
    volumes:
      - hits_redis_data:/data
    restart: always
    networks:
      - hits_network

volumes:
  hits_redis_data:

networks:
  hits_network:
    driver: bridge
